export const EVENTNEWS_LIST_REQUEST = "EVENTNEWS_LIST_REQUEST";
export const EVENTNEWS_LIST_SUCCESS = "EVENTNEWS_LIST_SUCCESS";
export const EVENTNEWS_LIST_FAIL = "EVENTNEWS_LIST_FAIL";

export const EVENTNEWS_DETAIL_REQUEST = "EVENTNEWS_DETAIL_REQUEST";
export const EVENTNEWS_DETAIL_SUCCESS = "EVENTNEWS_DETAIL_SUCCESS";
export const EVENTNEWS_DETAIL_FAIL = "EVENTNEWS_DETAIL_FAIL";
